name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libssl-dev cmake make clang patch
          pip3 install --upgrade buildozer cython

      - name: Build with Buildozer
        run: |
          # Создаем файл конфигурации для лицензий, если его нет
          mkdir -p ~/.android && touch ~/.android/repositories.cfg
          
          # Принимаем все лицензии Android SDK
          yes | sdkmanager --licenses || true
          
          # Запускаем сборку
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
